# node denotes consensus binary

story:
  vars:
    moniker: "Luganodes Story rpc 1"
    story_network_name: story-1
    cosmovisor_binary_url: https://github.com/cosmos/cosmos-sdk/releases/download/cosmovisor%2Fv1.7.3/cosmovisor-v1.7.3-linux-amd64.tar.gz
    story_geth_binary_url: https://github.com/piplabs/story-geth/releases/download/v1.2.3/geth-linux-amd64-v1.2.3
    story_node_binary_url: https://github.com/piplabs/story/releases/download/v1.8.0/story-linux-amd64
    story_geth_snapshot_url: https://server-2.itrocket.net/mainnet/story/geth_story_2026-09-15_22174513_snap.tar.lz4
    story_node_snapshot_url: https://server-2.itrocket.net/mainnet/story/story_2026-09-15_22174513_snap.tar.lz4
    story_geth_binary_version: v1.2.3
    story_node_binary_version: v1.8.0
    cosmovisor_binary_version: v1.7.3
    cosmovisor_archive_file_name: cosmovisor-v1.7.3-linux-amd64.tar.gz
    geth_service_name: geth.service
    cosmovisor_service_name: cosmovisor.service
    story_node_upgrade_height: 858000

  hosts:
    host1:
      ansible_host: host1
      ansible_user: user1
