- name: Create Snapshot download directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.story/snapshot"
    state: directory
    mode: "0750"

- name: Download geth snapshot asynchronously
  ansible.builtin.shell: >
    nohup aria2c -x16 -s16 --out=latest_geth_snapshot.tar.gz {{ story_geth_snapshot_url }} </dev/null >/home/{{ ansible_user }}/.story/snapshot/geth_download.log 2>&1 &
  args:
    chdir: "/home/{{ ansible_user }}/.story/snapshot"
    creates: "/home/{{ ansible_user }}/.story/snapshot/latest_geth_snapshot.tar.gz"
  async: 86400  # 24 hours async time 
  poll: 0


- name: Download story snapshot asynchronously
  ansible.builtin.shell: >
    nohup aria2c -x16 -s16 --out=latest_story_snapshot.tar.gz {{ story_node_snapshot_url }} </dev/null >/home/{{ ansible_user }}/.story/snapshot/story_download.log 2>&1 &
  args:
    chdir: "/home/{{ ansible_user }}/.story/snapshot"
    creates: "/home/{{ ansible_user }}/.story/snapshot/latest_story_snapshot.tar.gz"
  async: 86400  # 24 hours async time 
  poll: 0

