
- name: Create Cosmovisor download directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.story/cosmovisor_backup"
    state: directory
    mode: "0750"

- name: Initialize Cosmovisor
  ansible.builtin.command: 
    cmd: cosmovisor init /home/{{ ansible_user }}/.story/downloads/story-node/{{ story_node_binary_version }}/story
  environment:
    STORY_DATA_ROOT: "/home/{{ ansible_user }}/.story/story"
    DAEMON_HOME: "/home/{{ ansible_user }}/.story/story"
    DAEMON_NAME: "story"
    DAEMON_DATA_BACKUP_DIR: "/home/{{ ansible_user }}/.story/cosmovisor_backup"
  changed_when: false


- name: Copy cosmovisor systemd service template
  ansible.builtin.template:
    src: "cosmovisor.service.j2"
    dest: "/etc/systemd/system/cosmovisor.service"
    mode: '0644'
  become: true
